# Generated by Django 2.1.5 on 2019-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20190802_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(choices=[('Roshan Pandey', 'Roshan Pandey'), ('Bharat Hasija', 'Bharat Hasija')], default='Roshan Pandey', max_length=2),
        ),
    ]
